version: '3.8'
services:
  backend:
    build: ./backend/backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gizlo_vehiculo?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
  frontend:
    build: ./frontend/frontend
    ports:
      - "4200:80"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gizlo_vehiculo
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
